# Generated by Django 5.0.1 on 2024-02-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaApp', '0008_deliverydetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetail',
            name='card_exp',
            field=models.CharField(max_length=15),
        ),
    ]
