# Generated by Django 5.0.1 on 2024-02-15 14:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaApp', '0009_alter_deliverydetail_card_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_of_order',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
