# Generated by Django 5.0.1 on 2024-02-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaApp', '0010_order_date_of_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='garlic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pizza',
            name='jalepenos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pizza',
            name='pear',
            field=models.BooleanField(default=False),
        ),
    ]
