# Generated by Django 5.0.1 on 2024-02-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaApp', '0011_pizza_garlic_pizza_jalepenos_pizza_pear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetail',
            name='card_exp',
            field=models.CharField(max_length=5),
        ),
    ]
